package com.wordonline.account.service;

import java.util.List;

import org.springframework.dao.DuplicateKeyException;
import org.springframework.security.authorization.AuthorizationDeniedException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wordonline.account.domain.Authority;
import com.wordonline.account.domain.Member;
import com.wordonline.account.dto.JoinRequest;
import com.wordonline.account.dto.MemberPutRequest;
import com.wordonline.account.entity.AuthorityEntity;
import com.wordonline.account.entity.MemberAuthority;
import com.wordonline.account.entity.MemberEntity;
import com.wordonline.account.entity.Principal;
import com.wordonline.account.mapper.AuthorityMapper;
import com.wordonline.account.repository.AuthorityRepository;
import com.wordonline.account.repository.MemberAuthorityRepository;
import com.wordonline.account.repository.MemberRepository;
import com.wordonline.account.repository.PrincipalRepository;

import lombok.RequiredArgsConstructor;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@Service
@Transactional
@RequiredArgsConstructor
public class MemberService {

    private final MemberRepository memberRepository;
    private final MemberAuthorityRepository memberAuthorityRepository;
    private final AuthorityRepository authorityRepository;
    private final PrincipalRepository principalRepository;
    private final PasswordEncoder passwordEncoder;
    private final AuthorityMapper authorityMapper;

    /**
     * A guest presents no last password. The one it holds was generated by joinGuest(), handed to
     * the client and never chosen or seen by the user, so demanding it back protects nothing and
     * only locks an account the user has no other way to recover; the memberId claim on the
     * access token already proves who the caller is. A real member changing their email or
     * password still has to present it.
     */
    public Mono<Void> putMember(long memberId, MemberPutRequest putRequest) {
        return getMember(memberId)
                .flatMap(member -> {
                    // The short circuit is load-bearing: a guest sends no lastPassword, and
                    // PasswordEncoder.matches() answers a null raw password by throwing.
                    boolean mustPresentLastPassword = !member.isGuest();
                    if (mustPresentLastPassword && !member.validatePassword(
                            putRequest.lastPassword(), passwordEncoder)) {
                        return Mono.error(() -> new AuthorizationDeniedException("last password is not valid"));
                    }

                    String passwordHash = passwordEncoder.encode(putRequest.password());
                    member.setName(putRequest.name());
                    member.setEmail(putRequest.email());
                    member.setPasswordHash(passwordHash);
                    // The account now carries an email and a password its owner chose.
                    member.setGuest(false);

                    return memberRepository.save(new MemberEntity(member));
                })
                .onErrorMap(DuplicateKeyException.class, error -> new IllegalArgumentException("duplicated email", error))
                .then();
    }

    public Mono<Member> getMember(Long memberId) {
        Mono<MemberEntity> memberEntityMono = memberRepository.findById(memberId);
        return toMember(memberEntityMono);
    }

    public Mono<Member> getMember(String email) {
        Mono<MemberEntity> memberEntityMono = memberRepository.findByEmail(email);
        return toMember(memberEntityMono);
    }

    private Mono<Member> toMember(Mono<MemberEntity> memberEntityMono) {
        Flux<MemberAuthority> memberAuthorityFlux = memberEntityMono
                .flatMapMany(memberEntity -> memberAuthorityRepository.findAllByMemberId(
                        memberEntity.getId()));

        Flux<AuthorityEntity> authorityFlux = memberAuthorityFlux
                .flatMap(memberAuthority -> authorityRepository.findById(
                        memberAuthority.getAuthorityId()));

        return Mono.zip(memberEntityMono, authorityFlux.collectList())
                .flatMap(tuple -> {
                    MemberEntity memberEntity = tuple.getT1();
                    List<AuthorityEntity> authorityEntities = tuple.getT2();

                    Flux<Authority> authorityFluxMapped = Flux.fromIterable(authorityEntities)
                            .flatMap(authorityMapper::toDomain);

                    return authorityFluxMapped.collectList()
                            .map(memberEntity::toDomain);
                });
    }

    public Mono<Member> createMember(JoinRequest joinRequest) {
        return saveNewMember(joinRequest, false);
    }

    /**
     * The guest flag is decided here rather than carried on JoinRequest, so no caller of the
     * public join endpoint can ask to be created as a guest.
     */
    public Mono<Member> createGuest(JoinRequest joinRequest) {
        return saveNewMember(joinRequest, true);
    }

    private Mono<Member> saveNewMember(JoinRequest joinRequest, boolean guest) {
        return principalRepository.save(new Principal())
                .flatMap(
                        principal -> {
                            Member member = new Member(
                                    principal.getId(),
                                    joinRequest.name(),
                                    joinRequest.email(),
                                    passwordEncoder.encode(joinRequest.password()),
                                    guest
                            );
                            return memberRepository.save(new MemberEntity(member));
                        }
                ).map(MemberEntity::toDomain);
    }

    public Flux<Member> getSimpleMembers(long offset, int size) {
        return memberRepository.findPage(offset, size)
                .map(MemberEntity::toDomain);
    }

    public Mono<Long> getMemberCount() {
        return memberRepository.count();
    }

    public Mono<Void> deleteMember(long memberId) {
        return memberRepository.deleteById(memberId);
    }
}
